name: FenixShop
version: 1.0.0
main: me.laky.fenixshop.FenixShop
author: LAKY
description: Sistema de tienda para Minecraft 1.12.2

depend:
  - Vault

commands:
  shop:
    description: Abre la tienda
    usage: /shop
